"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "fr" | "es" | "de"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.tools": "Tools",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact",
    "nav.products": "Products",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.logout": "Logout",
    "nav.dashboard": "Dashboard",

    // Authentication
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.logout": "Logout",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Name",
    "auth.confirmPassword": "Confirm Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",

    "hero.new_ai_tools": "New AI Tools Available",
    "hero.transform_your": "Transform Your",
    "hero.media": "Media",
    "hero.instantly": "Instantly",
    "hero.description":
      "Professional AI-powered tools to edit, enhance, and transform your images and videos with just a few clicks.",
    "hero.start_editing": "Start Editing Free",
    "hero.view_pricing": "View Pricing",
    "hero.title": "Professional Media Tools",
    "hero.subtitle": "Transform your images and videos with our powerful AI-powered tools",
    "hero.cta": "Get Started Free",
    "hero.watchDemo": "Watch Demo",

    "stats.images_processed": "Images Processed",
    "stats.happy_users": "Happy Users",
    "stats.processing_time": "Avg Processing Time",
    "stats.success_rate": "Success Rate",

    "tools.powerful": "Powerful",
    "tools.tools": "Tools",
    "tools.subtitle": "Professional media editing tools powered by AI",
    "tools.bg_removal": "Background Removal",
    "tools.bg_removal_desc": "Remove backgrounds from images instantly with AI",
    "tools.format_converter": "Format Converter",
    "tools.format_converter_desc": "Convert between different image and video formats",
    "tools.image_compressor": "Image Compressor",
    "tools.image_compressor_desc": "Reduce file sizes without losing quality",
    "tools.watermark_remover": "Watermark Remover",
    "tools.watermark_remover_desc": "Remove unwanted watermarks from images",
    "tools.popular": "Popular",
    "tools.image_resizer": "Image Resizer",
    "tools.image_resizer_desc": "Resize images to any dimension while maintaining quality",
    "tools.video_compressor": "Video Compressor",
    "tools.video_compressor_desc": "Compress videos while maintaining quality",

    // Features
    "features.title": "Powerful Features",
    "features.subtitle": "Everything you need to edit your media",
    "features.why_choose": "Why Choose",
    "features.built_for_professionals": "Built for professionals, designed for everyone",
    "features.lightning_fast": "Lightning Fast",
    "features.lightning_fast_desc": "Process your media in seconds with our optimized AI algorithms",
    "features.privacy_first": "Privacy First",
    "features.privacy_first_desc": "Your files are processed securely and never stored on our servers",
    "features.ai_powered": "AI Powered",
    "features.ai_powered_desc": "Advanced machine learning models for professional-quality results",
    "features.backgroundRemoval": "Background Removal",
    "features.backgroundRemovalDesc": "Remove backgrounds from images instantly with AI",
    "features.imageCompression": "Image Compression",
    "features.imageCompressionDesc": "Reduce file sizes without losing quality",
    "features.formatConversion": "Format Conversion",
    "features.formatConversionDesc": "Convert between different image and video formats",
    "features.watermarkRemoval": "Watermark Removal",
    "features.watermarkRemovalDesc": "Remove unwanted watermarks from images",
    "features.imageResize": "Image Resize",
    "features.imageResizeDesc": "Resize images to any dimension",
    "features.videoCompression": "Video Compression",
    "features.videoCompressionDesc": "Compress videos while maintaining quality",

    // Tools
    "tools.title": "Our Tools",
    "tools.backgroundRemoval": "Background Removal",
    "tools.imageCompressor": "Image Compressor",
    "tools.formatConverter": "Format Converter",
    "tools.watermarkRemover": "Watermark Remover",
    "tools.imageResizer": "Image Resizer",
    "tools.videoCompressor": "Video Compressor",
    "tools.selectFile": "Select File",
    "tools.dragDrop": "Drag and drop your file here",
    "tools.processing": "Processing...",
    "tools.download": "Download Result",
    "tools.uploadAnother": "Upload Another",
    "tools.maxSize": "Max file size: 10MB",
    "tools.supportedFormats": "Supported formats",

    // Pricing
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Start free, upgrade when you need more",
    "pricing.free": "Free",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.save": "Save 20%",
    "pricing.getStarted": "Get Started",
    "pricing.contactUs": "Contact Us",
    "pricing.mostPopular": "Most Popular",

    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with our team - we're here to help you succeed",
    "contact.customer_support": "24/7 Customer Support",
    "contact.send_message": "Send us a Message",
    "contact.form_description": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.full_name": "Full Name",
    "contact.your_name": "Your name",
    "contact.department": "Department",
    "contact.choose_department": "Choose department",
    "contact.subject": "Subject",
    "contact.message_subject": "What can we help you with?",
    "contact.message": "Message",
    "contact.your_message": "Tell us more about your inquiry...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.message_sent": "Message Sent!",
    "contact.response_soon": "We'll get back to you within 24 hours.",
    "contact.email": "Email",
    "contact.email_desc": "Send us an email anytime",
    "contact.phone": "Phone",
    "contact.phone_desc": "Call us during business hours",
    "contact.live_chat": "Live Chat",
    "contact.live_chat_desc": "Chat with our support team",
    "contact.available_hours": "Available 24/7",
    "contact.address": "Address",
    "contact.address_desc": "Visit our office",
    "contact.office_hours": "Office Hours",
    "contact.monday_friday": "Monday - Friday",
    "contact.saturday": "Saturday",
    "contact.sunday": "Sunday",
    "contact.closed": "Closed",
    "contact.response_times": "Response Times",
    "contact.general_inquiries": "General Inquiries",
    "contact.within_24h": "Within 24 hours",
    "contact.technical_support": "Technical Support",
    "contact.within_4h": "Within 4 hours",
    "contact.urgent_issues": "Urgent Issues",
    "contact.within_1h": "Within 1 hour",
    "contact.general_inquiry": "General Inquiry",
    "contact.sales_products": "Sales & Products",
    "contact.partnerships": "Partnerships",
    "contact.press_media": "Press & Media",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.phone": "+1 (555) 123-4567",
    "contact.address": "123 Main St, City, State 12345",
    "contact.hours": "Mon-Fri 9AM-6PM EST",

    // Footer
    "footer.description": "Professional media editing tools powered by AI",
    "footer.quickLinks": "Quick Links",
    "footer.tools": "Tools",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    "footer.rights": "All rights reserved",
    "footer.newsletter": "Stay Updated",
    "footer.newsletter_desc": "Get the latest updates on new features and tools",
    "footer.subscribe": "Subscribe",
    "footer.subscribing": "Subscribing...",
    "footer.newsletter_success": "Subscribed!",
    "footer.newsletter_success_desc": "You'll receive our latest updates",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.remove": "Remove",
    "cart.quantity": "Quantity",
    "cart.continueShopping": "Continue Shopping",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.close": "Close",
    "common.file_too_large": "File too large. Please select a smaller file.",
    "common.invalid_format": "Invalid file format. Please select a supported format.",
    "common.processing_complete": "Processing complete!",
    "quality.login_required": "Login required for premium quality",

    "cta.ready_to_start": "Ready to get started?",
    "cta.join_thousands": "Join thousands of users who trust Pixel for their media editing needs",
    "cta.try_tools_now": "Try Tools Now",
    "cta.create_account": "Create Account",
    "cta.readyToStart": "Ready to get started?",
    "cta.joinThousands": "Join thousands of users who trust Pixel",
    "cta.startFree": "Start Free Today",
    "cta.noCredit": "No credit card required",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.tools": "Outils",
    "nav.pricing": "Tarifs",
    "nav.contact": "Contact",
    "nav.products": "Produits",
    "nav.login": "Connexion",
    "nav.signup": "S'inscrire",
    "nav.logout": "Déconnexion",
    "nav.dashboard": "Tableau de bord",

    // Authentication
    "auth.login": "Connexion",
    "auth.signup": "S'inscrire",
    "auth.logout": "Déconnexion",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.name": "Nom",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.noAccount": "Pas de compte ?",
    "auth.hasAccount": "Déjà un compte ?",

    "hero.new_ai_tools": "Nouveaux Outils IA Disponibles",
    "hero.transform_your": "Transformez Vos",
    "hero.media": "Médias",
    "hero.instantly": "Instantanément",
    "hero.description":
      "Outils professionnels alimentés par l'IA pour éditer, améliorer et transformer vos images et vidéos en quelques clics.",
    "hero.start_editing": "Commencer l'Édition Gratuite",
    "hero.view_pricing": "Voir les Tarifs",
    "hero.title": "Outils Média Professionnels",
    "hero.subtitle": "Transformez vos images et vidéos avec nos outils IA puissants",
    "hero.cta": "Commencer Gratuitement",
    "hero.watchDemo": "Voir la Démo",

    "stats.images_processed": "Images Traitées",
    "stats.happy_users": "Utilisateurs Satisfaits",
    "stats.processing_time": "Temps de Traitement Moyen",
    "stats.success_rate": "Taux de Réussite",

    "tools.powerful": "Outils",
    "tools.tools": "Puissants",
    "tools.subtitle": "Outils d'édition média professionnels alimentés par l'IA",
    "tools.bg_removal": "Suppression d'Arrière-plan",
    "tools.bg_removal_desc": "Supprimez les arrière-plans d'images instantanément avec l'IA",
    "tools.format_converter": "Convertisseur de Format",
    "tools.format_converter_desc": "Convertissez entre différents formats d'images et vidéos",
    "tools.image_compressor": "Compresseur d'Images",
    "tools.image_compressor_desc": "Réduisez la taille des fichiers sans perdre en qualité",
    "tools.watermark_remover": "Suppresseur de Filigrane",
    "tools.watermark_remover_desc": "Supprimez les filigranes indésirables des images",
    "tools.popular": "Populaire",
    "tools.image_resizer": "Redimensionneur d'Images",
    "tools.image_resizer_desc": "Redimensionnez les images à n'importe quelle dimension en maintenant la qualité",
    "tools.video_compressor": "Compresseur Vidéo",
    "tools.video_compressor_desc": "Compressez les vidéos en maintenant la qualité",

    // Features
    "features.title": "Fonctionnalités Puissantes",
    "features.subtitle": "Tout ce dont vous avez besoin pour éditer vos médias",
    "features.why_choose": "Pourquoi Choisir",
    "features.built_for_professionals": "Conçu pour les professionnels, pensé pour tous",
    "features.lightning_fast": "Ultra Rapide",
    "features.lightning_fast_desc": "Traitez vos médias en quelques secondes avec nos algorithmes IA optimisés",
    "features.privacy_first": "Confidentialité d'Abord",
    "features.privacy_first_desc": "Vos fichiers sont traités en sécurité et jamais stockés sur nos serveurs",
    "features.ai_powered": "Alimenté par l'IA",
    "features.ai_powered_desc":
      "Modèles d'apprentissage automatique avancés pour des résultats de qualité professionnelle",
    "features.backgroundRemoval": "Suppression d'Arrière-plan",
    "features.backgroundRemovalDesc": "Supprimez les arrière-plans d'images instantanément avec l'IA",
    "features.imageCompression": "Compression d'Images",
    "features.imageCompressionDesc": "Réduisez la taille des fichiers sans perdre en qualité",
    "features.formatConversion": "Conversion de Format",
    "features.formatConversionDesc": "Convertissez entre différents formats d'images et vidéos",
    "features.watermarkRemoval": "Suppression de Filigrane",
    "features.watermarkRemovalDesc": "Supprimez les filigranes indésirables des images",
    "features.imageResize": "Redimensionnement d'Image",
    "features.imageResizeDesc": "Redimensionnez les images à n'importe quelle dimension",
    "features.videoCompression": "Compression Vidéo",
    "features.videoCompressionDesc": "Compressez les vidéos en maintenant la qualité",

    // Tools
    "tools.title": "Nos Outils",
    "tools.backgroundRemoval": "Suppression d'Arrière-plan",
    "tools.imageCompressor": "Compresseur d'Images",
    "tools.formatConverter": "Convertisseur de Format",
    "tools.watermarkRemover": "Suppresseur de Filigrane",
    "tools.imageResizer": "Redimensionneur d'Images",
    "tools.videoCompressor": "Compresseur Vidéo",
    "tools.selectFile": "Sélectionner un Fichier",
    "tools.dragDrop": "Glissez et déposez votre fichier ici",
    "tools.processing": "Traitement en cours...",
    "tools.download": "Télécharger le Résultat",
    "tools.uploadAnother": "Télécharger un Autre",
    "tools.maxSize": "Taille max : 10MB",
    "tools.supportedFormats": "Formats supportés",

    // Pricing
    "pricing.title": "Choisissez Votre Plan",
    "pricing.subtitle": "Commencez gratuitement, améliorez quand vous en avez besoin",
    "pricing.free": "Gratuit",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Entreprise",
    "pricing.monthly": "Mensuel",
    "pricing.yearly": "Annuel",
    "pricing.save": "Économisez 20%",
    "pricing.getStarted": "Commencer",
    "pricing.contactUs": "Nous Contacter",
    "pricing.mostPopular": "Le Plus Populaire",

    "contact.title": "Nous Contacter",
    "contact.subtitle": "Entrez en contact avec notre équipe - nous sommes là pour vous aider à réussir",
    "contact.customer_support": "Support Client 24/7",
    "contact.send_message": "Envoyez-nous un Message",
    "contact.form_description": "Remplissez le formulaire ci-dessous et nous vous répondrons dès que possible.",
    "contact.full_name": "Nom Complet",
    "contact.your_name": "Votre nom",
    "contact.department": "Département",
    "contact.choose_department": "Choisir un département",
    "contact.subject": "Sujet",
    "contact.message_subject": "Comment pouvons-nous vous aider ?",
    "contact.message": "Message",
    "contact.your_message": "Parlez-nous de votre demande...",
    "contact.send": "Envoyer le Message",
    "contact.sending": "Envoi en cours...",
    "contact.message_sent": "Message Envoyé !",
    "contact.response_soon": "Nous vous répondrons dans les 24 heures.",
    "contact.email": "Email",
    "contact.email_desc": "Envoyez-nous un email à tout moment",
    "contact.phone": "Téléphone",
    "contact.phone_desc": "Appelez-nous pendant les heures d'ouverture",
    "contact.live_chat": "Chat en Direct",
    "contact.live_chat_desc": "Chattez avec notre équipe de support",
    "contact.available_hours": "Disponible 24/7",
    "contact.address": "Adresse",
    "contact.address_desc": "Visitez notre bureau",
    "contact.office_hours": "Heures d'Ouverture",
    "contact.monday_friday": "Lundi - Vendredi",
    "contact.saturday": "Samedi",
    "contact.sunday": "Dimanche",
    "contact.closed": "Fermé",
    "contact.response_times": "Temps de Réponse",
    "contact.general_inquiries": "Demandes Générales",
    "contact.within_24h": "Dans les 24 heures",
    "contact.technical_support": "Support Technique",
    "contact.within_4h": "Dans les 4 heures",
    "contact.urgent_issues": "Problèmes Urgents",
    "contact.within_1h": "Dans l'heure",
    "contact.general_inquiry": "Demande Générale",
    "contact.sales_products": "Ventes et Produits",
    "contact.partnerships": "Partenariats",
    "contact.press_media": "Presse et Médias",
    "contact.name": "Nom",
    "contact.email": "Email",
    "contact.phone": "+1 (555) 123-4567",
    "contact.address": "123 Main St, Ville, État 12345",
    "contact.hours": "Lun-Ven 9h-18h EST",

    // Footer
    "footer.description": "Outils d'édition média professionnels alimentés par l'IA",
    "footer.quickLinks": "Liens Rapides",
    "footer.tools": "Outils",
    "footer.legal": "Légal",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.cookies": "Politique des Cookies",
    "footer.rights": "Tous droits réservés",
    "footer.newsletter": "Restez Informé",
    "footer.newsletter_desc": "Recevez les dernières actualizaciones sobre nuevas funciones",
    "footer.subscribe": "S'abonner",
    "footer.subscribing": "Abonnement...",
    "footer.newsletter_success": "Abonné!",
    "footer.newsletter_success_desc": "Vous recevrez nos dernières mises à jour",

    // Cart
    "cart.title": "Panier",
    "cart.empty": "Votre panier est vide",
    "cart.total": "Total",
    "cart.checkout": "Commander",
    "cart.remove": "Supprimer",
    "cart.quantity": "Quantité",
    "cart.continueShopping": "Continuer les Achats",

    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.save": "Sauvegarder",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.close": "Fermer",
    "common.file_too_large": "Fichier trop volumineux. Veuillez sélectionner un fichier plus petit.",
    "common.invalid_format": "Format de fichier invalide. Veuillez sélectionner un format supporté.",
    "common.processing_complete": "Traitement terminé !",
    "quality.login_required": "Connexion requise pour la qualité premium",

    "cta.ready_to_start": "Prêt à commencer ?",
    "cta.join_thousands":
      "Rejoignez des milliers d'utilisateurs qui font confiance à Pixel pour leurs besoins d'édition média",
    "cta.try_tools_now": "Essayer les Outils Maintenant",
    "cta.create_account": "Créer un Compte",
    "cta.readyToStart": "Prêt à commencer ?",
    "cta.joinThousands": "Rejoignez des milliers d'utilisateurs qui font confiance à Pixel",
    "cta.startFree": "Commencer Gratuitement Aujourd'hui",
    "cta.noCredit": "No se requiere tarjeta de crédito",
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.tools": "Herramientas",
    "nav.pricing": "Precios",
    "nav.contact": "Contacto",
    "nav.products": "Productos",
    "nav.login": "Iniciar Sesión",
    "nav.signup": "Registrarse",
    "nav.logout": "Cerrar Sesión",
    "nav.dashboard": "Panel",

    // Authentication
    "auth.login": "Iniciar Sesión",
    "auth.signup": "Registrarse",
    "auth.logout": "Cerrar Sesión",
    "auth.email": "Email",
    "auth.password": "Contraseña",
    "auth.name": "Nombre",
    "auth.confirmPassword": "Confirmar Contraseña",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.hasAccount": "¿Ya tienes cuenta?",

    "hero.new_ai_tools": "Nuevas Herramientas IA Disponibles",
    "hero.transform_your": "Transforma Tus",
    "hero.media": "Medios",
    "hero.instantly": "Al Instante",
    "hero.description":
      "Herramientas profesionales impulsadas por IA para editar, mejorar y transformar tus imágenes y videos con solo unos clics.",
    "hero.start_editing": "Comenzar Edición Gratis",
    "hero.view_pricing": "Ver Precios",
    "hero.title": "Herramientas de Medios Profesionales",
    "hero.subtitle": "Transforma tus imágenes y videos con nuestras potentes herramientas de IA",
    "hero.cta": "Comenzar Gratis",
    "hero.watchDemo": "Ver Demo",

    "stats.images_processed": "Imágenes Procesadas",
    "stats.happy_users": "Usuarios Satisfechos",
    "stats.processing_time": "Tiempo de Procesamiento Promedio",
    "stats.success_rate": "Tasa de Éxito",

    "tools.powerful": "Herramientas",
    "tools.tools": "Potentes",
    "tools.subtitle": "Herramientas profesionales de edición de medios impulsadas por IA",
    "tools.bg_removal": "Eliminación de Fondo",
    "tools.bg_removal_desc": "Elimina fondos de imágenes al instante con IA",
    "tools.format_converter": "Convertidor de Formato",
    "tools.format_converter_desc": "Convierte entre diferentes formatos de imagen y video",
    "tools.image_compressor": "Compresor de Imágenes",
    "tools.image_compressor_desc": "Reduce el tamaño de archivos sin perder calidad",
    "tools.watermark_remover": "Eliminador de Marca de Agua",
    "tools.watermark_remover_desc": "Elimina marcas de agua no deseadas de las imágenes",
    "tools.popular": "Popular",
    "tools.image_resizer": "Redimensionador de Imágenes",
    "tools.image_resizer_desc": "Redimensiona imágenes a cualquier dimensión manteniendo la calidad",
    "tools.video_compressor": "Compresor de Video",
    "tools.video_compressor_desc": "Comprime videos manteniendo la calidad",

    // Features
    "features.title": "Características Potentes",
    "features.subtitle": "Todo lo que necesitas para editar tus medios",
    "features.why_choose": "¿Por Qué Elegir",
    "features.built_for_professionals": "Construido para profesionales, diseñado para todos",
    "features.lightning_fast": "Ultra Rápido",
    "features.lightning_fast_desc": "Procesa tus medios en segundos con nuestros algoritmos IA optimizados",
    "features.privacy_first": "Privacidad Primero",
    "features.privacy_first_desc":
      "Tus archivos se procesan de forma segura y nunca se almacenan en nuestros servidores",
    "features.ai_powered": "Impulsado por IA",
    "features.ai_powered_desc": "Modelos de aprendizaje automático avanzados para resultados de calidad profesional",
    "features.backgroundRemoval": "Eliminación de Fondo",
    "features.backgroundRemovalDesc": "Elimina fondos de imágenes al instante con IA",
    "features.imageCompression": "Compresión de Imágenes",
    "features.imageCompressionDesc": "Reduce el tamaño de archivos sin perder calidad",
    "features.formatConversion": "Conversión de Formato",
    "features.formatConversionDesc": "Convierte entre diferentes formatos de imagen y video",
    "features.watermarkRemoval": "Eliminación de Marca de Agua",
    "features.watermarkRemovalDesc": "Elimina marcas de agua no deseadas de las imágenes",
    "features.imageResize": "Redimensionar Imagen",
    "features.imageResizeDesc": "Redimensiona imágenes a cualquier dimensión",
    "features.videoCompression": "Compresión de Video",
    "features.videoCompressionDesc": "Comprime videos manteniendo la calidad",

    // Tools
    "tools.title": "Nuestras Herramientas",
    "tools.backgroundRemoval": "Eliminación de Fondo",
    "tools.imageCompressor": "Compresor de Imágenes",
    "tools.formatConverter": "Convertidor de Formato",
    "tools.watermarkRemover": "Eliminador de Marca de Agua",
    "tools.imageResizer": "Redimensionador de Imágenes",
    "tools.videoCompressor": "Compresor de Video",
    "tools.selectFile": "Seleccionar Archivo",
    "tools.dragDrop": "Arrastra y suelta tu archivo aquí",
    "tools.processing": "Procesando...",
    "tools.download": "Descargar Resultado",
    "tools.uploadAnother": "Subir Otro",
    "tools.maxSize": "Tamaño máx: 10MB",
    "tools.supportedFormats": "Formatos soportados",

    // Pricing
    "pricing.title": "Elige Tu Plan",
    "pricing.subtitle": "Comienza gratis, actualiza cuando necesites más",
    "pricing.free": "Gratis",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Empresa",
    "pricing.monthly": "Mensual",
    "pricing.yearly": "Anual",
    "pricing.save": "Ahorra 20%",
    "pricing.getStarted": "Comenzar",
    "pricing.contactUs": "Contáctanos",
    "pricing.mostPopular": "Más Popular",

    "contact.title": "Contáctanos",
    "contact.subtitle": "Ponte en contacto con nuestro equipo - estamos aquí para ayudarte a tener éxito",
    "contact.customer_support": "Soporte al Cliente 24/7",
    "contact.send_message": "Envíanos un Mensaje",
    "contact.form_description": "Completa el formulario a continuación y te responderemos lo antes posible.",
    "contact.full_name": "Nombre Completo",
    "contact.your_name": "Tu nombre",
    "contact.department": "Departamento",
    "contact.choose_department": "Elegir departamento",
    "contact.subject": "Asunto",
    "contact.message_subject": "¿En qué podemos ayudarte?",
    "contact.message": "Mensaje",
    "contact.your_message": "Cuéntanos más sobre tu consulta...",
    "contact.send": "Enviar Mensaje",
    "contact.sending": "Enviando...",
    "contact.message_sent": "¡Mensaje Enviado!",
    "contact.response_soon": "Te responderemos dentro de 24 horas.",
    "contact.email": "Email",
    "contact.email_desc": "Envíanos un email en cualquier momento",
    "contact.phone": "Teléfono",
    "contact.phone_desc": "Llámanos durante el horario comercial",
    "contact.live_chat": "Chat en Vivo",
    "contact.live_chat_desc": "Chatea con nuestro equipo de soporte",
    "contact.available_hours": "Disponible 24/7",
    "contact.address": "Dirección",
    "contact.address_desc": "Visita nuestra oficina",
    "contact.office_hours": "Horario de Oficina",
    "contact.monday_friday": "Lunes - Viernes",
    "contact.saturday": "Sábado",
    "contact.sunday": "Domingo",
    "contact.closed": "Cerrado",
    "contact.response_times": "Tiempos de Respuesta",
    "contact.general_inquiries": "Consultas Generales",
    "contact.within_24h": "Dentro de 24 horas",
    "contact.technical_support": "Soporte Técnico",
    "contact.within_4h": "Dentro de 4 horas",
    "contact.urgent_issues": "Problemas Urgentes",
    "contact.within_1h": "Dentro de 1 hora",
    "contact.general_inquiry": "Consulta General",
    "contact.sales_products": "Ventas y Productos",
    "contact.partnerships": "Asociaciones",
    "contact.press_media": "Prensa y Medios",
    "contact.name": "Nombre",
    "contact.email": "Email",
    "contact.phone": "+1 (555) 123-4567",
    "contact.address": "123 Main St, Ciudad, Estado 12345",
    "contact.hours": "Lun-Vie 9-18 Uhr EST",

    // Footer
    "footer.description": "Herramientas profesionales de edición de medios impulsadas por IA",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.tools": "Herramientas",
    "footer.legal": "Legal",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.cookies": "Política de Cookies",
    "footer.rights": "Todos los derechos reservados",
    "footer.newsletter": "Manténgase Actualizado",
    "footer.newsletter_desc": "Reciba las últimas actualizaciones sobre nuevas funciones",
    "footer.subscribe": "Suscribirse",
    "footer.subscribing": "Suscribiendo...",
    "footer.newsletter_success": "¡Suscrito!",
    "footer.newsletter_success_desc": "Recibirás nuestras últimas actualizaciones",

    // Cart
    "cart.title": "Carrito de Compras",
    "cart.empty": "Tu carrito está vacío",
    "cart.total": "Total",
    "cart.checkout": "Finalizar Compra",
    "cart.remove": "Eliminar",
    "cart.quantity": "Cantidad",
    "cart.continueShopping": "Continuar Comprando",

    // Common
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.close": "Cerrar",
    "common.file_too_large": "Archivo demasiado grande. Por favor selecciona un archivo más pequeño.",
    "common.invalid_format": "Formato de archivo inválido. Por favor selecciona un formato compatible.",
    "common.processing_complete": "¡Procesamiento completo!",
    "quality.login_required": "Se requiere iniciar sesión para calidad premium",

    "cta.ready_to_start": "¿Listo para comenzar?",
    "cta.join_thousands": "Únete a miles de usuarios que confían en Pixel para sus necesidades de edición de medios",
    "cta.try_tools_now": "Probar Herramientas Ahora",
    "cta.create_account": "Crear Cuenta",
    "cta.readyToStart": "¿Listo para comenzar?",
    "cta.joinThousands": "Únete a miles de usuarios que confían en Pixel",
    "cta.startFree": "Comenzar Gratis Hoy",
    "cta.noCredit": "No se requiere tarjeta de crédito",
  },
  de: {
    // Navigation
    "nav.home": "Startseite",
    "nav.tools": "Werkzeuge",
    "nav.pricing": "Preise",
    "nav.contact": "Kontakt",
    "nav.products": "Produkte",
    "nav.login": "Anmelden",
    "nav.signup": "Registrieren",
    "nav.logout": "Abmelden",
    "nav.dashboard": "Dashboard",

    // Authentication
    "auth.login": "Anmelden",
    "auth.signup": "Registrieren",
    "auth.logout": "Abmelden",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.name": "Name",
    "auth.confirmPassword": "Passwort bestätigen",
    "auth.forgotPassword": "Passwort vergessen?",
    "auth.noAccount": "Kein Konto?",
    "auth.hasAccount": "Bereits ein Konto?",

    "hero.new_ai_tools": "Neue KI-Tools Verfügbar",
    "hero.transform_your": "Transformieren Sie Ihre",
    "hero.media": "Medien",
    "hero.instantly": "Sofort",
    "hero.description":
      "Professionelle KI-gestützte Tools zum Bearbeiten, Verbessern und Transformieren Ihrer Bilder und Videos mit nur wenigen Klicks.",
    "hero.start_editing": "Kostenlos Bearbeiten Starten",
    "hero.view_pricing": "Preise Ansehen",
    "hero.title": "Professionelle Medien-Tools",
    "hero.subtitle": "Transformieren Sie Ihre Bilder und Videos mit unseren leistungsstarken KI-Tools",
    "hero.cta": "Kostenlos Starten",
    "hero.watchDemo": "Demo Ansehen",

    "stats.images_processed": "Verarbeitete Bilder",
    "stats.happy_users": "Zufriedene Nutzer",
    "stats.processing_time": "Durchschnittliche Verarbeitungszeit",
    "stats.success_rate": "Erfolgsrate",

    "tools.powerful": "Leistungsstarke",
    "tools.tools": "Werkzeuge",
    "tools.subtitle": "Professionelle Medienbearbeitungs-Tools powered by KI",
    "tools.bg_removal": "Hintergrund Entfernung",
    "tools.bg_removal_desc": "Entfernen Sie Hintergründe von Bildern sofort mit KI",
    "tools.format_converter": "Format-Konverter",
    "tools.format_converter_desc": "Konvertieren zwischen verschiedenen Bild- und Videoformaten",
    "tools.image_compressor": "Bildkompressor",
    "tools.image_compressor_desc": "Reduzieren Sie Dateigrößen ohne Qualitätsverlust",
    "tools.watermark_remover": "Wasserzeichen-Entferner",
    "tools.watermark_remover_desc": "Entfernen Sie unerwünschte Wasserzeichen von Bildern",
    "tools.popular": "Beliebt",
    "tools.image_resizer": "Bildgrößen-Änderer",
    "tools.image_resizer_desc": "Ändern Sie die Bildgröße auf jede Dimension bei gleichbleibender Qualität",
    "tools.video_compressor": "Video-Kompressor",
    "tools.video_compressor_desc": "Komprimieren Sie Videos bei gleichbleibender Qualität",

    // Features
    "features.title": "Leistungsstarke Funktionen",
    "features.subtitle": "Alles was Sie brauchen, um Ihre Medien zu bearbeiten",
    "features.why_choose": "Warum",
    "features.built_for_professionals": "Für Profis entwickelt, für alle konzipiert",
    "features.lightning_fast": "Blitzschnell",
    "features.lightning_fast_desc": "Verarbeiten Sie Ihre Medien in Sekunden mit unseren optimierten KI-Algorithmen",
    "features.privacy_first": "Datenschutz Zuerst",
    "features.privacy_first_desc": "Ihre Dateien werden sicher verarbeitet und niemals auf unseren Servern gespeichert",
    "features.ai_powered": "KI-Gestützt",
    "features.ai_powered_desc": "Fortschrittliche Machine-Learning-Modelle für professionelle Ergebnisse",
    "features.backgroundRemoval": "Hintergrund Entfernung",
    "features.backgroundRemovalDesc": "Entfernen Sie Hintergründe von Bildern sofort mit KI",
    "features.imageCompression": "Bildkompression",
    "features.imageCompressionDesc": "Reduzieren Sie Dateigrößen ohne Qualitätsverlust",
    "features.formatConversion": "Format-Konvertierung",
    "features.formatConversionDesc": "Konvertieren zwischen verschiedenen Bild- und Videoformaten",
    "features.watermarkRemoval": "Wasserzeichen Entfernung",
    "features.watermarkRemovalDesc": "Entfernen Sie unerwünschte Wasserzeichen von Bildern",
    "features.imageResize": "Bildgröße ändern",
    "features.imageResizeDesc": "Ändern Sie die Größe von Bildern auf jede Dimension",
    "features.videoCompression": "Video-Kompression",
    "features.videoCompressionDesc": "Komprimieren Sie Videos bei gleichbleibender Qualität",

    // Tools
    "tools.title": "Unsere Werkzeuge",
    "tools.backgroundRemoval": "Hintergrund Entfernung",
    "tools.imageCompressor": "Bildkompressor",
    "tools.formatConverter": "Format-Konverter",
    "tools.watermarkRemover": "Wasserzeichen-Entferner",
    "tools.imageResizer": "Bildgrößen-Änderer",
    "tools.videoCompressor": "Video-Kompressor",
    "tools.selectFile": "Datei Auswählen",
    "tools.dragDrop": "Ziehen Sie Ihre Datei hierher",
    "tools.processing": "Verarbeitung...",
    "tools.download": "Ergebnis Herunterladen",
    "tools.uploadAnother": "Weitere Hochladen",
    "tools.maxSize": "Max. Dateigröße: 10MB",
    "tools.supportedFormats": "Unterstützte Formate",

    // Pricing
    "pricing.title": "Wählen Sie Ihren Plan",
    "pricing.subtitle": "Starten Sie kostenlos, upgraden Sie wenn Sie mehr brauchen",
    "pricing.free": "Kostenlos",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Unternehmen",
    "pricing.monthly": "Monatlich",
    "pricing.yearly": "Jährlich",
    "pricing.save": "20% Sparen",
    "pricing.getStarted": "Loslegen",
    "pricing.contactUs": "Kontaktieren Sie uns",
    "pricing.mostPopular": "Am Beliebtesten",

    "contact.title": "Kontaktieren Sie uns",
    "contact.subtitle": "Nehmen Sie Kontakt mit unserem Team auf - wir sind hier, um Ihnen zum Erfolg zu verhelfen",
    "contact.customer_support": "24/7 Kundensupport",
    "contact.send_message": "Senden Sie uns eine Nachricht",
    "contact.form_description":
      "Füllen Sie das untenstehende Formular aus und wir melden uns so schnell wie möglich bei Ihnen.",
    "contact.full_name": "Vollständiger Name",
    "contact.your_name": "Ihr Name",
    "contact.department": "Abteilung",
    "contact.choose_department": "Abteilung wählen",
    "contact.subject": "Betreff",
    "contact.message_subject": "Womit können wir Ihnen helfen?",
    "contact.message": "Nachricht",
    "contact.your_message": "Erzählen Sie uns mehr über Ihre Anfrage...",
    "contact.send": "Nachricht Senden",
    "contact.sending": "Wird gesendet...",
    "contact.message_sent": "Nachricht Gesendet!",
    "contact.response_soon": "Wir melden uns innerhalb von 24 Stunden bei Ihnen.",
    "contact.email": "E-Mail",
    "contact.email_desc": "Senden Sie uns jederzeit eine E-Mail",
    "contact.phone": "Telefon",
    "contact.phone_desc": "Rufen Sie uns während der Geschäftszeiten an",
    "contact.live_chat": "Live-Chat",
    "contact.live_chat_desc": "Chatten Sie mit unserem Support-Team",
    "contact.available_hours": "24/7 Verfügbar",
    "contact.address": "Adresse",
    "contact.address_desc": "Besuchen Sie unser Büro",
    "contact.office_hours": "Bürozeiten",
    "contact.monday_friday": "Montag - Freitag",
    "contact.saturday": "Samstag",
    "contact.sunday": "Sonntag",
    "contact.closed": "Geschlossen",
    "contact.response_times": "Antwortzeiten",
    "contact.general_inquiries": "Allgemeine Anfragen",
    "contact.within_24h": "Innerhalb von 24 Stunden",
    "contact.technical_support": "Technischer Support",
    "contact.within_4h": "Innerhalb von 4 Stunden",
    "contact.urgent_issues": "Dringende Probleme",
    "contact.within_1h": "Innerhalb von 1 Stunde",
    "contact.general_inquiry": "Allgemeine Anfrage",
    "contact.sales_products": "Verkauf & Produkte",
    "contact.partnerships": "Partnerschaften",
    "contact.press_media": "Presse & Medien",
    "contact.name": "Name",
    "contact.email": "E-Mail",
    "contact.phone": "+1 (555) 123-4567",
    "contact.address": "123 Main St, Stadt, Staat 12345",
    "contact.hours": "Mo-Fr 9-18 Uhr EST",

    // Footer
    "footer.description": "Professionelle Medienbearbeitungs-Tools powered by KI",
    "footer.quickLinks": "Schnelle Links",
    "footer.tools": "Werkzeuge",
    "footer.legal": "Rechtliches",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.terms": "Nutzungsbedingungen",
    "footer.cookies": "Cookie-Richtlinie",
    "footer.rights": "Alle Rechte vorbehalten",
    "footer.newsletter": "Bleiben Sie auf dem Laufenden",
    "footer.newsletter_desc": "Erhalten Sie die neuesten Updates zu neuen Funktionen",
    "footer.subscribe": "Abonnieren",
    "footer.subscribing": "Abonnieren...",
    "footer.newsletter_success": "Abonniert!",
    "footer.newsletter_success_desc": "Sie erhalten unsere neuesten Updates",

    // Cart
    "cart.title": "Warenkorb",
    "cart.empty": "Ihr Warenkorb ist leer",
    "cart.total": "Gesamt",
    "cart.checkout": "Zur Kasse",
    "cart.remove": "Entfernen",
    "cart.quantity": "Menge",
    "cart.continueShopping": "Weiter Einkaufen",

    // Common
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
    "common.back": "Zurück",
    "common.next": "Weiter",
    "common.previous": "Vorherige",
    "common.close": "Schließen",
    "common.file_too_large": "Datei zu groß. Bitte wählen Sie eine kleinere Datei.",
    "common.invalid_format": "Ungültiges Dateiformat. Bitte wählen Sie ein unterstütztes Format.",
    "common.processing_complete": "Verarbeitung abgeschlossen!",
    "quality.login_required": "Anmeldung erforderlich für Premium-Qualität",

    "cta.ready_to_start": "Bereit anzufangen?",
    "cta.join_thousands":
      "Schließen Sie sich Tausenden von Benutzern an, die Pixel für ihre Medienbearbeitungsbedürfnisse vertrauen",
    "cta.try_tools_now": "Tools Jetzt Ausprobieren",
    "cta.create_account": "Konto Erstellen",
    "cta.readyToStart": "Bereit anzufangen?",
    "cta.joinThousands": "Schließen Sie sich Tausenden von Benutzern an, die Pixel vertrauen",
    "cta.startFree": "Heute Kostenlos Starten",
    "cta.noCredit": "Keine Kreditkarte erforderlich",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
